{{- $baasRepoPwSecret := index (lookup "v1" "Secret" .Release.Namespace "baas-repo-pw") }}

apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "lagoon-core.fullname" . }}-baas-repo-pw"
type: Opaque
data:
{{- if $baasRepoPwSecret }}
  repo-pw:  {{ $baasRepoPwSecret.data "repo-pw" }}
{{ else }} # install operation
  repo-pw: {{ randAlphaNum 28 | b64enc }}
{{ end }}
