{{- if .Values.nats.enabled -}}
{{- if .Values.natsConfig.tls.secretData }}
---
{{/*
This secret must have a static name because the nats subchart is configured to
use this secret via the lagoon-core values.yaml.
*/}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: lagoon-core-nats-tls
  labels:
    {{- include "lagoon-core.labels" . | nindent 4 }}
stringData:
  {{- with .Values.natsConfig.tls.secretData }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
---
{{/*
This secret must have a static name because the nats subchart is configured to
use this secret via the lagoon-core values.yaml.
*/}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: lagoon-core-nats-conf
  labels:
    {{- include "lagoon-core.labels" . | nindent 4 }}
stringData:
  accounts.conf: |
    accounts: {
      lagoonRemote: {
        LAGOON_REMOTE = {
          publish: "lagoon.sshportal.remote",
          subscribe: "_INBOX.>"
        }
        SSHPORTAL_API = {
          publish: "_INBOX.>",
          subscribe: "lagoon.sshportal.api"
        }
        users: [
        {{- range .Values.natsConfig.users.lagoonRemote }}
          {
            user: {{ .user | quote }},
            permissions: $LAGOON_REMOTE
          },
        {{- end }}
          {
            user: "lagoon-core-local",
            permissions: $SSHPORTAL_API
          },
        ]
      }
    }
    no_auth_user: "lagoon-core-local"
  leafnodesAuthorization.conf: |
    authorization: {
      users: [
      {{- range .Values.natsConfig.users.lagoonRemote }}
        {
          user: {{ .user | quote }}
          password: {{ .password | quote }}
          account: lagoonRemote
        },
      {{- end }}
      ]
    }
{{- end }}
